name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./vin-checker-frontend

      - name: Build Angular app
        run: npm run build -- --base-href /vin-checker-app/
        working-directory: ./vin-checker-frontend

      - name: Debug - Check build output
        run: |
          echo "Checking build output directory:"
          ls -la ./vin-checker-frontend/dist/
          echo "Contents of dist folder:"
          ls -la ./vin-checker-frontend/dist/*/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vin-checker-frontend/dist/browser
          enable_jekyll: false
